Feature/add agitator system
Team488/TeamXbot2017 pull request #12
Opened 2017-01-28 22:46 UTC by tfrancisco

2017-01-28 22:48 UTC, JohnGilb commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +    }
There's nothing that stops the agitator!

Either make these commands run "whileHeld" or add an additional button that's bound to a stop command.

2017-01-28 22:48 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/SubsystemDefaultCommandMap.java
> +        agitatorSubsystem.setDefaultCommand(stop);
Good call. =]

2017-01-28 22:49 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/agitator/AgitatorSubsystem.java
> +        motorPowerProperty = propManager.createPersistentProperty("agitator motor power", 0.5);
capitalize "Agitator"

2017-01-28 22:49 UTC, JohnGilb commented on Competition2017/tests/competition/subsystems/agitator/AgitatorSubsystemTest.java
> +    }
I suggest at least one more test - 1st, have the agitator go forwards, then stop it. Verify that it go forwards then stops.

2017-01-28 22:50 UTC, JohnGilb requested changes
See my comments above

2017-01-28 23:10 UTC, JohnGilb approved these changes
lgtm!

2017-01-29 01:50 UTC, merged

2017-01-29 02:31 UTC, WasabiFan reviewed
This has already been merged, but there are some things that should still be fixed.

2017-01-29 02:31 UTC, WasabiFan commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +        oi.leftButtons.getifAvailable(5).whenPressed(stop);
This is unnecessary. The default command is to stop, so this just takes up an extra button without purpose.

2017-01-29 02:31 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/agitator/AgitatorSubsystem.java
> +        agitatorMotor.setBrakeEnableDuringNeutral(true);
This should be false, I think. I don't see a reason for it to prevent itself from spinning, and it could get in the way.

2017-01-29 02:31 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/agitator/AgitatorSubsystem.java
> +
Remove whitespace