Changed autonomus use low gear
Team488/TeamXbot2017 pull request #122
Opened 2017-03-25 18:13 UTC by imathno

2017-03-25 20:03 UTC, aschokking requested changes

2017-03-25 20:03 UTC, aschokking commented on Competition2017/src/competition/subsystems/autonomous/DriveToBoilerUsingHeuristicsWithVisionCommandGroup.java
> +        addSequential(shiftCommand);
I don't think shiftGearCommand will currently end so this would hold everything else up, maybe add a short timeout, 100ms?

2017-03-25 20:03 UTC, aschokking commented on Competition2017/src/competition/subsystems/autonomous/DriveToBoilerWithTriangleVisionCommandGroup.java
> +        this.addSequential(shiftCommand);
same thing here, probably want a short timeout

2017-03-25 21:56 UTC, aschokking approved these changes

2017-03-25 23:15 UTC, merged

2017-03-26 21:19 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +        this.addSequential(driveToHopper, 0.1);
Are you _sure_ this is what you want to do?

2017-03-26 22:06 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +        this.addSequential(driveToHopper, 0.1);
Fixed by https://github.com/Team488/TeamXbot2017/pull/128; we really need to be more careful in reviews!