unjam agitator and shooter commands and tests
Team488/TeamXbot2017 pull request #132
Opened 2017-03-31 03:00 UTC by tfrancisco

2017-04-01 14:08 UTC, aschokking commented
@tfrancisco could you take a stab at the merge conflicts?

2017-04-01 14:10 UTC, aschokking commented on Competition2017/src/competition/subsystems/shooter_wheel/commands/UnjamShooterWheelCommand.java
> +    private ShooterWheelSubsystem subsystem;
I think BaseShooterWheelCommand already has this variable for you?

2017-04-04 05:04 UTC, WasabiFan requested changes

2017-04-04 05:04 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/agitator/commands/IntakeAgitatorCommand.java
> +                .createPersistentProperty(" threshold for agitator motor current before unjamming", 10);
Remove preceeding space and capitalize first word (here and below)

2017-04-04 05:04 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/agitator/commands/IntakeAgitatorCommand.java
> +        if (agitatorSubsystem.getMotorCurrent() >= motorCurrentThreshold.get()) {
Can we add some logic here so that it requires the current to be above the threshold for some amount of time? With the current logic, a ball momentarily jamming would cause the ejection to start even though it wasn't necessary.

2017-04-04 05:04 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/agitator/commands/IntakeAgitatorCommand.java
> +            mostRecentEjectTimeSet = false;
Could this variable be more clearly named `isUnjamming`?

2017-04-04 05:04 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/shooter_wheel/ShooterWheelSubsystem.java
> +    public double getMotorPower(){
What is "power"?

2017-04-04 05:04 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/shooter_wheel/commands/UnjamShooterWheelCommand.java
> +        if (subsystem.getMotorSpeed() >= 0 && subsystem.getMotorSpeed() <= threshold.get()
What is this command intended to do? It will just spin the wheel backwards as far as I can tell, given that there is nothing attempting to move it forward. What does this do over a straight "reverse" command?

2017-04-04 05:04 UTC, WasabiFan commented on Competition2017/tests/competition/subsystems/agitator/AgitatorSubsystemTest.java
> +
Remove this

2017-04-04 05:04 UTC, WasabiFan commented on Competition2017/tests/competition/subsystems/agitator/AgitatorTestBase.java
> +    public void setUp() {
This one was fun to debug 😆

2017-04-04 05:04 UTC, WasabiFan commented on .idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
😒

2017-04-04 05:04 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/shoot_fuel/RightShootFuelAndAgitateCommandGroup.java
> +        RunIntakeAgitatorIfWheelAtSpeedCommand intake = new RunIntakeAgitatorIfWheelAtSpeedCommand(agitatorsManagerSubsystem.getRightAgitator(),
Fix indentation

2017-04-04 05:10 UTC, imathno commented on .idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
uhoh

2017-04-04 14:53 UTC, aschokking commented on Competition2017/src/competition/subsystems/shooter_wheel/commands/UnjamShooterWheelCommand.java
> +public class UnjamShooterWheelCommand extends BaseShooterWheelCommand {
Did we have instances of balls jammed in the wheels? I only recall agitator/belts

2017-04-04 14:56 UTC, aschokking commented
Once we have something we like for the agitator, might be nice to do something similar for the collector and belts.

2017-04-04 14:56 UTC, aschokking requested changes

2017-04-04 14:56 UTC, aschokking commented on Competition2017/src/competition/subsystems/shooter_wheel/commands/UnjamShooterWheelCommand.java
> +        super(shooterWheelsManagerSubsystem.getLeftShooter());
this is hardcoded to left :(

2017-04-04 14:56 UTC, aschokking commented on Competition2017/src/competition/subsystems/shooter_wheel/commands/UnjamShooterWheelCommand.java
> +    @Inject
shouldn't be injectable

2017-04-04 16:37 UTC, imathno commented on Competition2017/src/competition/subsystems/shooter_wheel/commands/UnjamShooterWheelCommand.java
> +        super(shooterWheelsManagerSubsystem.getLeftShooter());
That what I thought because it was originally getting the left shooter so I just 
assumed just to use the left.

2017-04-04 20:15 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/shooter_wheel/commands/UnjamShooterWheelCommand.java
> +public class UnjamShooterWheelCommand extends BaseShooterWheelCommand {
Yeah, I'd be scared of a system which monitors wheel current and acts upon detected jamming... remember that the motor uses 20+ amps for 3+ seconds when spinning up the flywheel.

2017-04-04 20:16 UTC, WasabiFan commented
This seems to have been lost in the conversation earlier, so I'll post it again...

> https://github.com/Team488/TeamXbot2017/pull/132/files#diff-2d81918b9454c7ef5bb1748ce1d9b9a0R25
> What is this command intended to do? It will just spin the wheel backwards as far as I can tell, given that there is nothing attempting to move it forward. What does this do over a straight "reverse" command?

2017-04-06 01:10 UTC, closed without merging