Generic autonomous command setter
Team488/TeamXbot2017 pull request #145
Opened 2017-04-15 21:33 UTC by aschokking

* Removes boiler plate code with setting auto commands
* Ensures the commands are only constructed at initialize time of the command so any properties being read in the command group constructors are applied each time the button is pressed
* Refactor alliance color logic to the command group constructor

2017-04-15 21:37 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/autonomous/selection/GenericAutonomousCommandSetter.java
> +
needs a `log.info("Initializing")` or something along those lines

2017-04-15 21:50 UTC, aschokking commented on Competition2017/src/competition/subsystems/autonomous/selection/GenericAutonomousCommandSetter.java
> +
added

2017-04-18 15:34 UTC, WasabiFan requested changes

2017-04-18 15:34 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/autonomous/selection/GenericAutonomousCommandSetter.java
> +
Remove superfluous whitespace

2017-04-18 15:34 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/autonomous/ShootAndDriveAcrossBaseLineCommandGroup.java
> +        log.info("Setting alliance to " + poseSubsystem.getAllianceColor() + " alliance");
This isn't something the pose subsystem should be responsible for.

2017-04-18 15:34 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/autonomous/ShootAndDriveAcrossBaseLineCommandGroup.java
> +        log.info("Setting alliance to " + poseSubsystem.getAllianceColor() + " alliance");
This logging shouldn't be done in individual commands; can we move this?

2019-09-28 18:42 UTC, closed without merging