Feature/autonomous
Team488/TeamXbot2017 pull request #19
Opened 2017-02-04 22:43 UTC by tfrancisco

2017-02-04 23:13 UTC, JohnGilb requested changes

2017-02-04 23:13 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +    private class TimeoutCommand extends BaseCommand {
You should probably just add this command to the SeriouslyCommonLib, with a public setTimeout method.

2017-02-04 23:13 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +        if(goToBoiler.get()){
This approach will require us to create commands like this at the start of autonomous - I've added a work item in our backlog to track this : https://app.asana.com/0/38541457243752/262705727435797

2017-02-04 23:13 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +        // move to turning point on baseline
Add a comment saying where you expect the robot to be starting, and in what orientation.

2017-02-04 23:13 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/drive/DriveSubsystem.java
> +    public final XGyro imu;
Given that you're working from the DriveToOrientation branch, we should probably wait for that to get checked in before merging your changes.

2017-02-04 23:22 UTC, aschokking commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +    private class TimeoutCommand extends BaseCommand {
also why is this class `private`?

2017-02-04 23:23 UTC, aschokking commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +    private class TimeoutCommand extends BaseCommand {
and that setTimeout method should accept a `DoubleProperty` as well to allow easy tuning

2017-02-04 23:25 UTC, aschokking commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +        DriveForDistanceCommand driveForDistance = driveForDistanceProvider.get();
it might be nice to name this variable which drive command it is, eg `moveToTurningPointCommand`

2017-02-04 23:28 UTC, aschokking requested changes

2017-02-04 23:28 UTC, aschokking commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +        driveForDistance.setDeltaDistance(distanceFromTurningPointToHopper.get());
you'll need to create a 2nd DriveForDistance command, here by re-using the previous one it's actually going to break and use this value for the command.

2017-02-04 23:28 UTC, aschokking commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +            driveToOrientation.setHeading(headingToFaceBoiler.get());
same thing with this DriveToOrientation, you need to create multiple instances, one per unique thing you want to do.

2017-02-05 03:44 UTC, WasabiFan requested changes

2017-02-05 03:44 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +    public DoubleProperty distanceFromWallToBaseline;
These should be private.

2017-02-05 03:44 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/autonomous/DriveToHopperThenBoilerCommandGroup.java
> +        distanceFromWallToBaseline = propManager.createPersistentProperty("distanceFromWallToBaselineInInches", 37.25);
Names should be just like sentences; spaces between words as well.

2017-02-15 04:38 UTC, aschokking approved these changes
Nice job! Next step test it! Maybe at a smaller scale of shorter distances

2017-02-17 02:57 UTC, JohnGilb approved these changes

2017-02-17 03:11 UTC, WasabiFan approved these changes
It would be nice to change the property strings to fit sentence case.

2017-02-17 03:13 UTC, merged