Configured the follower motor
Team488/TeamXbot2017 pull request #35
Opened 2017-02-10 04:02 UTC by imathno

2017-02-10 04:13 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/shooter_wheel/ShooterWheelSubsystem.java
> +        masterMotor.createTelemetryProperties(side + "Shooter wheel master", propManager);
Add a space in the string between the number and "shooter" (also, decapitalize "Shooter")

2017-02-10 04:13 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/shooter_wheel/ShooterWheelSubsystem.java
> +        follower.configPeakOutputVoltage(12, -6);
I believe the follower needs to spin backwards relative to the master. That should be configured, and additionally these values may need to be swapped. Or they could probably just be removed, given that the master constraints should apply here too.

2017-02-10 04:13 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/shooter_wheel/ShooterWheelSubsystem.java
> +        masterMotor.createTelemetryProperties(side + "Shooter wheel master", propManager);
Does something update the telemetry?

2017-02-10 04:22 UTC, imathno commented on Competition2017/src/competition/subsystems/shooter_wheel/ShooterWheelSubsystem.java
> +        masterMotor.createTelemetryProperties(side + "Shooter wheel master", propManager);
"but it can buy me a boat" done

2017-02-10 04:30 UTC, imathno commented on Competition2017/src/competition/subsystems/shooter_wheel/ShooterWheelSubsystem.java
> +        masterMotor.createTelemetryProperties(side + "Shooter wheel master", propManager);
done

2017-02-10 04:30 UTC, imathno commented on Competition2017/src/competition/subsystems/shooter_wheel/ShooterWheelSubsystem.java
> +        follower.configPeakOutputVoltage(12, -6);
done

2017-02-11 02:51 UTC, JohnGilb requested changes

2017-02-11 02:51 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/shooter_wheel/ShooterWheelSubsystem.java
> +        follower.configPeakOutputVoltage(-12, 6);
I'm pretty sure this also needs to be `12, -6` based on some earlier readthroughs of the CANTalon code,

2017-02-11 15:52 UTC, aschokking commented on Competition2017/src/competition/subsystems/shooter_wheel/ShooterWheelSubsystem.java
> +        follower.configPeakOutputVoltage(12, -6);
Is the currently physically modeled config the same as the 2016 summer bot shooter?

2017-02-11 17:56 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/shooter_wheel/ShooterWheelSubsystem.java
> +        follower.configPeakOutputVoltage(-12, 6);
I think the proper way to invert this is to call `follower.setInverted(true)`, though we should verify that actually works on-robot =]

2017-02-11 20:17 UTC, JohnGilb approved these changes

2017-02-11 21:36 UTC, merged