Feature/collector
Team488/TeamXbot2017 pull request #4
Opened 2017-01-21 23:11 UTC by Unagifan

Completed Outline for Collector System and Commands. Successfully tested on 2016 Summer Bot.

2017-01-21 23:14 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +        collectorMotor = factory.getCANTalonSpeedController(5);
Let's use the logger! The drive subsystem also does this:
log.info("Creating CollectorSubsystem");

2017-01-21 23:17 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/collector/commands/EjectCollectorCommand.java
> +
Create a logger for this class in the constructor, and use it here:

"initializing EjectCollectorCommand"

2017-01-21 23:17 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/collector/commands/IntakeCollectorCommand.java
> +
Add loggers for all the new commands =]

2017-01-22 02:39 UTC, WasabiFan requested changes

2017-01-22 02:39 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/commands/EjectCollectorCommand.java
> +import sun.util.logging.resources.logging;
Remove this; it isn't the right import.

2017-01-22 02:39 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/commands/EjectCollectorCommand.java
> +    private static Logger log = Logger.getLogger(CollectorSubsystem.class);
This logger points to the wrong parent class!

2017-01-22 02:39 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/commands/IntakeCollectorCommand.java
> +    private static Logger log = Logger.getLogger(CollectorSubsystem.class);
Wrong parent class

2017-01-22 02:39 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/commands/StopCollectorCommand.java
> +    private static Logger log = Logger.getLogger(CollectorSubsystem.class);
Wrong parent class

2017-01-22 02:39 UTC, WasabiFan commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +            CollectorSubsystem collector,
Remove this parameter if it isn't used.

2017-01-22 02:39 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/SubsystemDefaultCommandMap.java
> +        collectorSystem.setDefaultCommand(stop);
Remove unused params

2017-01-22 02:39 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +        collectorMotor.setProfile(1);
Is there a particular reason for using profile 1? If not, use 0.

2017-01-22 02:39 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +        ejectSpeedProperty = propManager.createPersistentProperty("Collector Eject Speed:", -0.5);
Remove colons, and later words can be lowercased. Only capitalizing the first letter makes it easier to spot the start of a property.

2017-01-22 02:39 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/commands/StopCollectorCommand.java
> +        collectorSystem.stop();
All commands should either run every execute or run just in initialize. Don't mix.

2017-01-22 16:33 UTC, aschokking commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +        ejectSpeedProperty = propManager.createPersistentProperty("Collector Eject Speed:", -0.5);
Might be something nice to document on the wiki somewhere (both how to use the property system and naming conventions for properties)

2017-01-25 03:08 UTC, Unagifan commented on Competition2017/src/competition/subsystems/collector/commands/EjectCollectorCommand.java
> +import sun.util.logging.resources.logging;
Removed

2017-01-25 03:09 UTC, Unagifan commented on Competition2017/src/competition/subsystems/collector/commands/EjectCollectorCommand.java
> +    private static Logger log = Logger.getLogger(CollectorSubsystem.class);
Yup! Got it

2017-01-25 03:09 UTC, Unagifan commented on Competition2017/src/competition/subsystems/collector/commands/IntakeCollectorCommand.java
> +    private static Logger log = Logger.getLogger(CollectorSubsystem.class);
Got it

2017-01-25 03:09 UTC, Unagifan commented on Competition2017/src/competition/subsystems/collector/commands/StopCollectorCommand.java
> +    private static Logger log = Logger.getLogger(CollectorSubsystem.class);
Yah

2017-01-25 03:12 UTC, Unagifan commented on Competition2017/src/competition/subsystems/collector/commands/StopCollectorCommand.java
> +        collectorSystem.stop();
Yah!

2017-01-25 03:13 UTC, Unagifan commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +            CollectorSubsystem collector,
COOL

2017-01-25 03:15 UTC, Unagifan commented on Competition2017/src/competition/subsystems/SubsystemDefaultCommandMap.java
> +        collectorSystem.setDefaultCommand(stop);
Yup!

2017-01-25 03:16 UTC, Unagifan commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +        collectorMotor.setProfile(1);
Oh I didn't realize it was zero indexed

2017-01-25 03:23 UTC, Unagifan commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +        ejectSpeedProperty = propManager.createPersistentProperty("Collector Eject Speed:", -0.5);
Yup got it!!

2017-01-25 03:33 UTC, JohnGilb approved these changes

2017-01-25 03:34 UTC, WasabiFan requested changes

2017-01-25 03:34 UTC, WasabiFan commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +        oi.rightButtons.getifAvailable(1).whenPressed(stop);
Since the stop command is the default, it seems like we shouldn't need a separate "stop" button.

2017-01-25 03:34 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +import com.ctre.CANTalon;
Why is this import here? That's worrying; we shouldn't need it.

2017-01-25 03:34 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +        ejectSpeedProperty = propManager.createPersistentProperty("Collector eject speed", -0.5);
This is "power" instead of "speed".

2017-01-25 03:34 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/commands/StopCollectorCommand.java
> +        log.info("Stopping Collector");
This log line should match the others in related commands. I'd prefer "Initializing <someName>Command" or "Starting <someName>Command".

2017-01-25 03:35 UTC, Unagifan commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +        oi.rightButtons.getifAvailable(1).whenPressed(stop);
!

2017-01-25 03:37 UTC, Unagifan commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +        ejectSpeedProperty = propManager.createPersistentProperty("Collector eject speed", -0.5);
!

2017-01-25 03:38 UTC, Unagifan commented on Competition2017/src/competition/subsystems/collector/commands/StopCollectorCommand.java
> +        log.info("Stopping Collector");
!

2017-01-25 03:42 UTC, Unagifan commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +import com.ctre.CANTalon;
COOL

2017-01-25 03:55 UTC, WasabiFan approved these changes
Looks great! It sounds like @Unagifan might be making minor whitespace changes right now, so confirm with him before merging.

2017-01-25 04:08 UTC, merged