Feature/collector tests
Team488/TeamXbot2017 pull request #6
Opened 2017-01-27 03:09 UTC by Unagifan

Created Tests for the Collector Subsystems. 
Changed some variables in the Collector Subsystem to Public

2017-01-27 06:26 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +    public final DoubleProperty intakePowerProperty;
I am reluctant to use public properties. I think we have the infrastructure to change values without access to the property objects, and we could also subclass these things for tests and have the subclasses expose either the properties or setters publicly.

2017-01-27 06:26 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/collector/CollectorSubsystem.java
> +    public final XCANTalon collectorMotor;
😟

2017-01-27 06:26 UTC, WasabiFan commented on Competition2017/tests/competition/subsystems/collector/CollectorSubsystemTest.java
> +
Remove unnecessary whitespace

2017-01-27 06:26 UTC, WasabiFan commented on Competition2017/tests/competition/subsystems/collector/CollectorTestBase.java
> +        collect = injector.getInstance(CollectorSubsystem.class);
Is this how we do things?

2017-01-28 18:17 UTC, Unagifan commented on Competition2017/tests/competition/subsystems/collector/CollectorSubsystemTest.java
> +
got it!

2017-01-28 18:52 UTC, WasabiFan requested changes
I like this pattern! Just some small comments for tidying up. Nice job on the quick implementation.

2017-01-28 18:52 UTC, WasabiFan commented on Competition2017/tests/competition/subsystems/collector/MockCollectorSubsystem.java
> +        // TODO Auto-generated constructor stub
This has been implemented, so we can remove the TODO

2017-01-28 18:52 UTC, WasabiFan commented on Competition2017/tests/competition/subsystems/collector/MockCollectorSubsystem.java
> +    public XCANTalon getMotor(){
Do we actually use this? I don't see any calls to it.

2017-01-28 18:52 UTC, WasabiFan commented on Competition2017/tests/competition/subsystems/collector/MockCollectorSubsystem.java
> +    public DoubleProperty getIntake(){
Can we append the word `Prop` or `Property` to make it clear what the purpose is?

2017-01-28 18:52 UTC, WasabiFan commented on Competition2017/tests/competition/subsystems/collector/MockCollectorSubsystem.java
> +public class MockCollectorSubsystem extends CollectorSubsystem {
I think the intent would be clearer here if it were called `TestCollectorSubsystem`: the word "mock" is used elsewhere to refer to versions of classes that don't actually do what they claim to. In this case, it's just a version which is opened up for testing.

2017-01-28 19:02 UTC, Unagifan commented on Competition2017/tests/competition/subsystems/collector/MockCollectorSubsystem.java
> +public class MockCollectorSubsystem extends CollectorSubsystem {
:)

2017-01-28 19:02 UTC, Unagifan commented on Competition2017/tests/competition/subsystems/collector/MockCollectorSubsystem.java
> +        // TODO Auto-generated constructor stub
👍

2017-01-28 19:02 UTC, Unagifan commented on Competition2017/tests/competition/subsystems/collector/MockCollectorSubsystem.java
> +    public XCANTalon getMotor(){
Oops!

2017-01-28 19:10 UTC, Unagifan commented
Having problems with Smart Git might have to restart Pull request

2017-01-28 19:14 UTC, WasabiFan commented
I might be able to help you resolve that from the command line.

2017-01-28 19:35 UTC, Unagifan commented
Never Mind! I got it working again!

2017-01-28 19:40 UTC, WasabiFan approved these changes
One small thing to fix before merging; other than that, looks great!

2017-01-28 19:40 UTC, WasabiFan commented on Competition2017/tests/competition/subsystems/collector/TestCollectorSubsystem.java
> +        // TODO Auto-generated constructor stub
This is implemented, so the comment can be removed

2017-01-28 19:47 UTC, tfrancisco commented on Competition2017/tests/competition/subsystems/collector/CollectorTestBase.java
> +    public void verifyCollectSetpoints(double power){
Add a comment to explain what this method is doing.

2017-01-28 19:48 UTC, tfrancisco commented on Competition2017/tests/competition/subsystems/collector/CollectorSubsystemTest.java
> +        verifyCollectSetpoints(0);
why 0?

2017-01-28 20:33 UTC, Unagifan commented on Competition2017/tests/competition/subsystems/collector/CollectorSubsystemTest.java
> +        verifyCollectSetpoints(0);
I chose 0 because the power of the Collector Motor should be 0 when the stop command is being command.

2017-01-28 20:39 UTC, Unagifan commented
Thanks Kaelin!

2017-01-28 20:40 UTC, WasabiFan commented on Competition2017/tests/competition/subsystems/collector/CollectorTestBase.java
> +    //Tests to see if the motor is running at the given power.
Hint: type `/**` and hit enter. The comment that is generated is called a "Javadoc" comment; it is detected specially by Eclipse and shows a caller the description you provide.

2017-01-28 20:41 UTC, merged