Feature/initial oi mapping
Team488/TeamXbot2017 pull request #64
Opened 2017-02-18 23:44 UTC by Unagifan

Initial Oi mapping for robot testing of actuators.

2017-02-18 23:50 UTC, JohnGilb requested changes

2017-02-18 23:50 UTC, JohnGilb commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +        ascend.includeOnSmartDashboard("Climber ascend");
I think these commands need to be whileHeld - just because if we don't stop them in time, we could damage the machine.

2017-02-18 23:50 UTC, aschokking requested changes

2017-02-18 23:50 UTC, aschokking commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> -        oi.leftButtons.getifAvailable(2).whileHeld(descend);
I think we'll still want these OI buttons

2017-02-18 23:52 UTC, Unagifan commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +        ascend.includeOnSmartDashboard("Climber ascend");
!

2017-02-18 23:52 UTC, Unagifan commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> -        oi.leftButtons.getifAvailable(2).whileHeld(descend);
!

2017-02-18 23:57 UTC, aschokking approved these changes

2017-02-19 00:43 UTC, JohnGilb commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +
remove this blank line

2017-02-19 00:43 UTC, JohnGilb commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +
and this one

2017-02-19 00:44 UTC, JohnGilb commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +
remove this blank line

2017-02-19 00:44 UTC, JohnGilb commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +
remove this blank line

2017-02-19 00:44 UTC, JohnGilb commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +
remove this blank line

2017-02-19 00:44 UTC, JohnGilb requested changes
see comments

2017-02-19 00:52 UTC, JohnGilb approved these changes

2017-02-19 00:53 UTC, merged