Created Climbing subsystem, commands, and controller.
Team488/TeamXbot2017 pull request #7
Opened 2017-01-27 04:16 UTC by SethNguyenXBOT

2017-01-27 06:19 UTC, WasabiFan requested changes

2017-01-27 06:19 UTC, WasabiFan commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +        oi.leftButtons.getifAvailable(3).whileHeld(descend);
Question for whomever knows: what happens when both buttons are held? Does the latest-started one win?

2017-01-27 06:19 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/ClimbingSubsystem.java
> +
Remove extraneous spacing (other files too)

2017-01-27 06:19 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/ClimbingSubsystem.java
> +        log.info("Creating Collector Subsystem");
🔍🤔

2017-01-27 06:19 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/ClimbingSubsystem.java
> +        descendPowerProperty = propManager.createPersistentProperty("Climber descend power", -0.5);
Nice naming!

2017-01-27 06:19 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/ClimbingSubsystem.java
> +        climbingMotor.setBrakeEnableDuringNeutral(false);
I think this might be an instance where we want to enable breaking. That's only if we are using a CIM though.

2017-01-27 06:19 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/ClimbingSubsystem.java
> +
Remove extraneous spacing

2017-01-27 06:19 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/commands/ClimbClimbingCommand.java
> +public class ClimbClimbingCommand extends BaseCommand {
I think we can improve this name. What about incorporating the term `ascend` (here and in other files)?

2017-01-27 06:19 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/commands/ClimbClimbingCommand.java
> +        climbingSystem.intake();
Intake?

2017-01-28 19:39 UTC, tfrancisco commented on Competition2017/src/competition/subsystems/climbing/ClimbingSubsystem.java
> +        climbingMotor.setBrakeEnableDuringNeutral(false);
Why do we set this false and what does setBrakeEnableDuringNeutral do?

2017-01-28 20:27 UTC, aschokking commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +        oi.leftButtons.getifAvailable(3).whileHeld(descend);
I 'think' they fight each other back and forth for whileHeld.

2017-01-28 20:28 UTC, aschokking commented on Competition2017/src/competition/subsystems/climbing/commands/ClimbClimbingCommand.java
> +        climbingSystem.intake();
copy and pasted from the collector

2017-01-28 20:38 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/SubsystemDefaultCommandMap.java
> +    public void setupClimbingSubsystem(ClimbingSubsystem climbingSystem,StopClimbingCommand stop){
We should alphabetize these so that there aren't so many merge conflicts.

2017-01-28 20:38 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/ClimbingSubsystem.java
> +        climbingMotor.setBrakeEnableDuringNeutral(true);
Are we sure we want to do this? This is only OK if we're using a CIM.

2017-01-28 20:38 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/ClimbingSubsystem.java
> +        climbingMotor.setProfile(0);
This should go before setting any other properties.

2017-01-28 20:38 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/commands/AscendClimbingCommand.java
> +    final ClimbingSubsystem ascendingSystem;
These names should match.

2017-01-28 20:38 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/commands/AscendClimbingCommand.java
> +public class AscendClimbingCommand extends BaseCommand {
It seems like we could simplify this name without losing meaning; what about `AscendCommand`?

2017-01-28 20:38 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/climbing/commands/AscendClimbingCommand.java
> +        log.info("Initializing AscendAscendingCommand");
This log line should match the command name

2017-01-28 22:20 UTC, aschokking commented on Competition2017/src/competition/subsystems/climbing/commands/AscendClimbingCommand.java
> +    final ClimbingSubsystem ascendingSystem;
ie, just name this variable `climbingSubsystem`

2017-01-28 22:23 UTC, aschokking commented
You've also got some merge conflicts to resolve, you'll want to pull master and then Integrate Develop

2017-02-03 02:16 UTC, aschokking commented on Competition2017/src/competition/subsystems/climbing/commands/AscendCommand.java
> +    public AscendCommand(ClimbingSubsystem ascendingSystem){
this should be `climbingSystem` for consistency

2017-02-03 02:17 UTC, aschokking approved these changes

2017-02-03 04:05 UTC, merged

2017-02-03 04:56 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/SubsystemDefaultCommandMap.java
> +        public void setupCollectorSubsystem(CollectorSubsystem collectorSystem,StopCollectorCommand stop) {
This shouldn't be indented