Added ability to convert inches per second into ticks per 10ms. Added…
Team488/TeamXbot2017 pull request #81
Opened 2017-03-01 04:27 UTC by SethNguyenXBOT

… test to see if new ability works.

2017-03-03 03:15 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/drive/DriveSubsystem.java
> +    public void tankDriveVelocityPercentMax(double leftPower, double rightPower) {
rename these arguments to something like `leftVelocityPercent` and `rightVelocityPercent`

2017-03-03 03:16 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/drive/DriveSubsystem.java
> +        leftDrive.set(convertInchesToTicks(leftInchesPerSec)/100.0);
you say 10ms in the comment above, but the code here is dividing by 100ms. Which is right?

2017-03-03 03:37 UTC, WasabiFan commented on Competition2017/src/competition/subsystems/drive/DriveSubsystem.java
> +        leftDrive.set(convertInchesToTicks(leftInchesPerSec)/100.0);
`per 1000ms` / `100` = `per 10 ms`

2017-03-04 15:59 UTC, aschokking commented on Competition2017/src/competition/subsystems/drive/DriveSubsystem.java
> +        //Converting inches per second to ticks per 10ms
Nit, space after `// `

2017-03-04 16:00 UTC, aschokking requested changes

2017-03-04 16:00 UTC, aschokking commented on Competition2017/tests/competition/subsystems/drive/DriveSubsystemTest.java
> +    public void testUpdatePeriodicDataTest(){
This was deleted in another commit, probably a bad merge left it here, safe to delete again from your branch.

2017-03-04 18:45 UTC, aschokking approved these changes

2017-03-08 03:51 UTC, merged