Rationalized OI button mapping.
Team488/TeamXbot2017 pull request #82
Opened 2017-03-03 02:54 UTC by SethNguyenXBOT

2017-03-03 03:05 UTC, aschokking commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +        oi.controller.getXboxButton(XboxButton.LeftStick).whileHeld(runBeltLeft);
So to fire the shooter someone will hold down on a given side: Stick, Bumper and Trigger?
I'm wondering if we can simplify that down a bit now that we have a mostly functioning robot, for instance can we have 1 button that spins up the shooter and runs the belt while at speed?

2017-03-03 03:51 UTC, JohnGilb requested changes
We need the commands that set the shooters to speed goals to be on the gamepad. Right now they are on the joysticks.

2017-03-03 07:21 UTC, WasabiFan commented
Remember that you have the D-pad to work with too... that might make more sense for ascend/descend.

2017-03-04 15:57 UTC, aschokking commented
unless something has changed, the last time it was tested I believe the dpad wasn't functioning

2017-03-04 16:39 UTC, WasabiFan commented
How so? The interface was implemented, so if there's a bug preventing it from getting data, that should be investigated.

2017-03-04 18:38 UTC, JohnGilb approved these changes

2017-03-04 18:44 UTC, aschokking approved these changes

2017-03-04 18:44 UTC, aschokking commented
we should write this mapping down somewhere that we can keep near the OI

2017-03-04 18:45 UTC, merged