Implemented 2017 OI Panel buttons.
Team488/TeamXbot2017 pull request #85
Opened 2017-03-04 20:07 UTC by SethNguyenXBOT

2017-03-04 20:30 UTC, aschokking commented on Competition2017/src/competition/operator_interface/OperatorInterface.java
> +    public XJoystick operatorJoystick;
let's call it operatorPanelJoystick just to be extra explicit

2017-03-04 20:30 UTC, aschokking commented on Competition2017/src/competition/operator_interface/OperatorInterface.java
> +    public JoystickButtonManager operatorButtons;
and operatorPanelButtons

2017-03-04 20:33 UTC, WasabiFan commented on Competition2017/src/competition/operator_interface/OperatorCommandMap.java
> +       shiftLow.setGear(Gear.LOW_GEAR);
Remove trailing whitespace

2017-03-10 04:10 UTC, JohnGilb approved these changes

2017-03-10 04:12 UTC, JohnGilb requested changes
Move the shoot command groups from `setupShooterWheelCommands()` into your new `setupShooterCommandGroup()`

2017-03-11 18:32 UTC, JohnGilb approved these changes

2017-03-11 18:33 UTC, merged