Added method to set the threshold for DriveToPointUsingHeuristicsCommand
Team488/TeamXbot2017 pull request #93
Opened 2017-03-11 19:06 UTC by imathno

2017-03-11 19:14 UTC, JohnGilb requested changes

2017-03-11 19:14 UTC, JohnGilb commented on Competition2017/.classpath
> +	<classpathentry kind="var" path="opencv" sourcepath="opencv.sources"/>
don't include changes to this file

2017-03-11 19:14 UTC, JohnGilb commented on Competition2017/src/competition/subsystems/drive/commands/DriveToPointUsingHeuristicsCommand.java
> +    private void setThreshold(double error, boolean derivative, double time) {
This needs to be more clear about which PIDs it is influencing

2017-03-11 19:15 UTC, imathno commented on Competition2017/.classpath
> +	<classpathentry kind="var" path="opencv" sourcepath="opencv.sources"/>
I thought I ignored the classpath file

2017-03-12 01:08 UTC, JohnGilb approved these changes

2017-03-12 01:08 UTC, merged